const productsList = [
    {
        id: 1,
        category: "فساتين",
        image: "/products/dresses/floral-dress.png",
        name: "فستان مشجر",
        description: "فستان وردي عصري بألوان جريئة يناسب إطلالاتك اليومية",
        colors: ["#FFD1DC"],
        price: 150,
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 2,
        category: "فساتين",
        image: "/products/dresses/Summer-dress.png",
        name: "فستان صيفي",
        description: "فستان أخضر خفيف بتصميم فاخر لإطلالة أنثوية رائعة",
        colors: ["#478960"],
        price: 95,
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 3,
        category: "فساتين",
        image: "/products/dresses/Winter-dress.png",
        name: "فستان شتوي",
        description: " بلمسات فاخرة مزين بالترتر يمنحك إطلالة ساحرة وأنيقة.",
        colors: ["#608BC1", "#FFD1DC", "#000000"],
        price: 100,
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 4,
        category: "فساتين",
        image: "/products/dresses/Striped-dress.png",
        name: "فستان مخطط",
        description: "فستان أسود أنيق مزين بتفاصيل دقيقة، يمنحك إطلالة فاخرة.",
        colors: ["#000000", "#133E87"],
        price: 120,
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 5,
        category: "فساتين",
        image: "/products/dresses/Wavy-dress.png",
        name: "فستان مموج",
        description: "فستان زهري رائع بإطلالة جذابة تضفي لمسة من الأناقة.",
        colors: ["#FFD1DC", "#133E87"],
        price: 150,
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 6,
        category: "فساتين",
        image: "/products/dresses/Modern-dress.png",
        name: "فستان عصري",
        description: "فستان أبيض عصري بتصميم مبتكر يناسب كل المناسبات.",
        colors: ["#FFD1DC", "#FFFFFF"],
        price: 150,
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 7,
        category: "فساتين",
        image: "/products/dresses/black-dress.webp",
        name: "فستان مخمل",
        description: "فستان مخمل بتصميم مبتكر يناسب كل المناسبات.",
        colors: ["#000000"],
        price: 250,
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 8,
        category: "فساتين",
        image: "/products/dresses/Casual-dress.jpg",
        name: "فستان كاجوال",
        description: "فستان مع ازهار بتصميم مبتكر يناسب كل المناسبات.",
        colors: ["#608BC1"],
        price: 60,
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 9,
        category: "أحذية",
        image: "/products/shoes/Adidas-shoes.avif",
        name: "حذاء رياضي",
        description: "حذاء مريح وخفيف مصمم للأنشطة الرياضية والمشي",
        colors: ["#000000"],
        price: 80,
        sizes: ["S", "M", "L"],
    },
    {
        id: 10,
        category: "أحذية",
        image: "/products/shoes/Heels.webp",
        name: "حذاء بكعب",
        description: "حذاء أنيق مزود بكعب مرتفع",
        colors: ["#FFD1DC"],
        price: 90,
        sizes: ["S", "M"],
    },
    {
        id: 11,
        category: "حقائب",
        image: "/products/bags/dior.jpg",
        name: "حقيبة يد",
        description: "حقيبة فاخرة تتميز بتصميم أنيق وعصري",
        colors: ["#478960"],
        price: 700,
        sizes: ["M"],
    },
    {
        id: 12,
        category: "حقائب",
        image: "/products/bags/prada.jpg",
        name: "حقيبة يد",
        description: "حقيبة عملية وأنيقة لحمل الأغراض",
        colors: ["#608BC1"],
        price: 200,
        sizes: ["M", "L"],
    },
    {
        id: 13,
        category: "اكسسوارات",
        image: "/products/accessories/hand-accessories.webp",
        name: "اكسسوارات يد",
        description: "قطع تضيف لمسة من الجمال والأناقة لليد",
        colors: ["#FFFFFF"],
        price: 50,
        sizes: ["XL"],
    },
    {
        id: 14,
        category: "اكسسوارات",
        image: "/products/accessories/Hair-accessories.jpg",
        name: "اكسسوارات شعر",
        description: "قطع تزيين الشعر وتضيف لمسة مميزة.",
        colors: ["#FFFFFF"],
        price: 20,
        sizes: ["S", "M", "L", "XL"],
    },
];

export default productsList;
